name: customer_web
description: Flutter Web-App for customers of polyus autopark.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  intl: ^0.17.0
  web_socket_channel: ^2.2.0
  http: ^0.13.5
  timetable: ^1.0.0-alpha.10
  flutter_timetable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Stem
      fonts:
        - asset: assets/fonts/Stem-Regular.otf
          weight: 400
        - asset: assets/fonts/Stem-Thin.otf
          weight: 100
        - asset: assets/fonts/Stem-Medium.otf
          weight: 500
        - asset: assets/fonts/Stem-Light.otf
          weight: 300
        - asset: assets/fonts/Stem-Bold.otf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
